---
- name: Vector | Download
  ansible.builtin.get_url:
    url: "{{ vector_url }}"
    dest: "./vector-{{ vector_version }}.x86_64.rpm"
    mode: "0644"
- name: Vector | Install
  become: true
  ansible.builtin.yum:
    name: "./vector-{{ vector_version }}.x86_64.rpm"
    disable_gpg_check: true
